# This is the name of the GitHub Actions workflow.
name: Python Application CI

# This section defines when the workflow will run.
on:
  # Run on every push to the 'main' branch.
  push:
    branches: [ "main" ]
  # Also run on pull requests targeting the 'main' branch.
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build".
  build:
    # The type of runner that the job will run on. 'ubuntu-latest' is a standard choice.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Step 1: Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Check out repository code
        uses: actions/checkout@v3

      # Step 2: Sets up a Python environment for use in actions.
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Installs the project dependencies from requirements.txt.
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Step 4: Runs the unit tests using the 'discover' command.
      - name: Run tests
        run: |
          python -m unittest discover
